version: '3.8'

services:
  api:
    build: .
    container_name: objective_rental_api
    ports:
      - "2342:2342"
    environment:
      - PORT=${PORT}
      - MONGO_URL=${MONGO_URL}
      - DB_NAME=${DB_NAME}
    depends_on:
      mongodb:
        condition: service_started
    volumes:
      - ./src:/app/src

  mongodb:
    image: mongo:latest
    container_name: objective_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: >
      mongod --quiet --setParameter logComponentVerbosity='{"network":{"verbosity":-1},"accessControl":{"verbosity":-1}}'

volumes:
  mongo_data: