version: '3.8'

services:
  api:
    build: .
    container_name: objective_rental_api
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/rental_db
      - PORT=3000
    depends_on:
      mongodb:
        condition: service_started
    volumes:
      - ./src:/app/src

  mongodb:
    image: mongo:latest
    container_name: objective_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: >
      mongod --quiet --setParameter logComponentVerbosity='{"network":{"verbosity":-1},"accessControl":{"verbosity":-1}}'

volumes:
  mongo_data: