export enum ErrorCode {
  MOVIE_NOT_AVAILABLE_FOR_BOOKING = 'MOVIE_NOT_AVAILABLE_FOR_BOOKING',
  RESERVATION_NOT_FOUND = 'RESERVATION_NOT_FOUND',
  RESERVATION_EXPIRED_OR_ALREADY_PROCESSED = 'RESERVATION_EXPIRED_OR_ALREADY_PROCESSED',
  RENTAL_RECORD_NOT_FOUND = 'RENTAL_RECORD_NOT_FOUND',
  MOVIE_ALREADY_RETURNED_OR_NOT_LEASED = 'MOVIE_ALREADY_RETURNED_OR_NOT_LEASED',
  INVALID_INPUT = 'INVALID_INPUT',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
